name       : perl-moo
version    : '2.003006'
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Moo-2.003006.tar.gz : bcb2092ab18a45005b5e2e84465ebf3a4999d8e82a43a09f5a94d859ae7f2472
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Moo - Minimalist Object Orientation (with Moose compatibility)
description: |
    Moo - Minimalist Object Orientation (with Moose compatibility)
builddeps  :
    - perl-class-method-modifiers
    - perl-devel-globaldestruction
    - perl-module-runtime
    - perl-role-tiny
    - perl-scalar-list-utils
    - perl-sub-quote
rundeps    :
    - perl-class-method-modifiers
    - perl-devel-globaldestruction
    - perl-module-runtime
    - perl-role-tiny
    - perl-scalar-list-utils
    - perl-sub-quote
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
