name       : perl-moo
version    : '2.005005'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Moo-2.005005.tar.gz : fb5a2952649faed07373f220b78004a9c6aba387739133740c1770e9b1f4b108
homepage   : https://metacpan.org/pod/Moo
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Moo - Minimalist Object Orientation (with Moose compatibility)
description: |
    Moo - Minimalist Object Orientation (with Moose compatibility)
builddeps  :
    - perl-class-method-modifiers
    - perl-devel-globaldestruction
    - perl-module-runtime
    - perl-role-tiny
    - perl-scalar-list-utils
    - perl-sub-quote
rundeps    :
    - perl-class-method-modifiers
    - perl-devel-globaldestruction
    - perl-module-runtime
    - perl-role-tiny
    - perl-scalar-list-utils
    - perl-sub-quote
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
